
name: "projectsdiscovery"
description: "build, tag and pushes the container"
author: "w3security<@w3security>"

branding:
  icon: "anchor"
  color: "blue"

runs:
  using: docker
  image: docker://w3security/gitscan:v0.4.0

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

outputs:
  TAG_NAME:
    description: "Your Docker Tag name."
