name: docker-build

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Dockerfile
        run: |
          mkdir build
          cat > build/Dockerfile<<EOF
          FROM alpine
          RUN echo "hello world"
          ENTRYPOINT [ "sh", "-c", "echo -n 'Machine: ' && uname -m && echo -n 'Bits: ' && getconf LONG_BIT && echo 'goodbye world'" ]
          EOF
      - name: Build & Push to Docker Hub
        uses: w3security/gitscan@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: build/Dockerfile
          IMAGE_NAME: w3security/gitscan
          TAG_NAME: action-docker
          BUILDX: "true"
